version: '3'
services:
  thread:
    image: multithreading-benchmark
    container_name: thread
    build: ./
    volumes:
      - ./run.js:/opt/multithreading/run.js:ro
      - ./index.html:/opt/multithreading/index.html:ro
    ports:
      - 9000:8000
    environment:
      - DEBUG=true
      - REBUILD=true
      - PORT=8000